"""initial schema

Revision ID: 6cb3f6176920
Revises: 
Create Date: 2026-09-23 12:30:04.947408
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


revision: str = '6cb3f6176920'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=1024), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'checksum', name='uq_documents_library_checksum')
    )
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('canonical_source_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_target_name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('pronouns', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'canonical_source_name', name='uq_entities_library_source_name')
    )
    op.create_index('ix_entities_library_type', 'entities', ['library_id', 'entity_type'], unique=False)
    op.create_table('glossary_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('source_term', sa.String(length=255), nullable=False),
    sa.Column('target_term', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'source_term', name='uq_glossary_library_source_term')
    )
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('source_embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'sequence_number', name='uq_chunks_document_sequence')
    )
    op.create_index('ix_chunks_document_sequence', 'chunks', ['document_id', 'sequence_number'], unique=False)
    op.create_index('ix_chunks_source_embedding_hnsw', 'chunks', ['source_embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'source_embedding': 'vector_cosine_ops'})
    op.create_table('entity_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'language', 'alias', name='uq_entity_aliases_entity_language_alias')
    )
    op.create_index('ix_entity_aliases_lookup', 'entity_aliases', ['language', 'alias'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('subject_entity_id', sa.Uuid(), nullable=False),
    sa.Column('predicate', sa.String(length=128), nullable=False),
    sa.Column('object_entity_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'subject_entity_id', 'predicate', 'object_entity_id', name='uq_relationships_fact')
    )
    op.create_table('translation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('library_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_embedding_hnsw', 'memories', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_memories_library_type', 'memories', ['library_id', 'memory_type'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retrieved_context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'version', name='uq_translations_chunk_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translations')
    op.drop_index('ix_memories_library_type', table_name='memories')
    op.drop_index('ix_memories_embedding_hnsw', table_name='memories')
    op.drop_table('memories')
    op.drop_table('translation_runs')
    op.drop_table('relationships')
    op.drop_index('ix_entity_aliases_lookup', table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index('ix_chunks_source_embedding_hnsw', table_name='chunks')
    op.drop_index('ix_chunks_document_sequence', table_name='chunks')
    op.drop_table('chunks')
    op.drop_table('glossary_entries')
    op.drop_index('ix_entities_library_type', table_name='entities')
    op.drop_table('entities')
    op.drop_table('documents')
    op.drop_table('libraries')
    # ### end Alembic commands ###